In [1]:
import numpy as np
import pandas as pd

In [5]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [6]:
df = pd.read_csv('covid_toy.csv')

In [7]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [8]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [9]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [10]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [14]:
X_train

age  gender  fever   cough       city
88    5  Female  100.0    Mild    Kolkata
18   64  Female   98.0    Mild  Bangalore
53   83    Male   98.0    Mild      Delhi
55   81  Female  101.0    Mild     Mumbai
92   82  Female  102.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
22   71  Female   98.0  Strong    Kolkata
83   17  Female  104.0    Mild    Kolkata
24   13  Female  100.0  Strong    Kolkata
1    27    Male  100.0    Mild      Delhi
68   54  Female  104.0  Strong    Kolkata

[80 rows x 5 columns]

1. Without ColumnTransformer

In [17]:
#adding simple imputer to fever column
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

#also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever

array([[100.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [102.        ],
       [ 99.        ],
       [100.        ],
       [104.        ],
       [101.        ],
       [100.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [103.        ],
       [ 99.        ],
       [103.        ],
       [ 98.        ],
       [100.82857143],
       [100.82857143],
       [ 99.        ],
       [100.        ],
       [ 98.        ],
       [102.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [ 98.        ],
       [100.82857143],
       [103.        ],
       [104.        ],
       [100.        ],
       [101.        ],
       [101.        ],
       [101.        ],
       [103.        ],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [ 99.        ],
       [104.        ],
       [ 99.        ],
       [100.82857143],
       [ 99.        ],
       [101

In [18]:
X_train_fever.shape

(80, 1)

In [21]:
#Ordinalencoding on cough col
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

#also test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_test_cough

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [23]:
X_train_cough.shape

(80, 1)

In [24]:
#OneHotEncoding on gender,city
ohe = OneHotEncoder(drop='first',sparse=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

#also with test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],


In [25]:
X_train_gender_city.shape

(80, 4)

In [26]:
#Extracting age col
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

#also test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age

array([[ 5],
       [64],
       [83],
       [81],
       [82],
       [60],
       [10],
       [44],
       [47],
       [11],
       [12],
       [81],
       [42],
       [16],
       [59],
       [60],
       [69],
       [71],
       [42],
       [22],
       [80],
       [ 5],
       [33],
       [14],
       [10],
       [56],
       [31],
       [23],
       [46],
       [25],
       [19],
       [19],
       [20],
       [ 8],
       [73],
       [83],
       [83],
       [23],
       [49],
       [18],
       [65],
       [38],
       [65],
       [42],
       [ 6],
       [27],
       [82],
       [55],
       [64],
       [79],
       [20],
       [19],
       [75],
       [50],
       [51],
       [66],
       [12],
       [26],
       [34],
       [34],
       [74],
       [84],
       [15],
       [24],
       [20],
       [82],
       [73],
       [51],
       [16],
       [69],
       [34],
       [11],
       [65],
       [51],
       [14],
       [71],
       [17],

In [27]:
X_train_age.shape

(80, 1)

In [28]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)

#also test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_test_transformed

array([[ 40.,  98.,   0.,   1.,   0.,   0.,   1.],
       [ 69., 103.,   0.,   0.,   1.,   0.,   0.],
       [ 49., 102.,   0.,   1.,   0.,   0.,   0.],
       [ 80.,  98.,   0.,   1.,   0.,   0.,   0.],
       [ 47., 100.,   0.,   0.,   0.,   0.,   1.],
       [ 68., 101.,   0.,   1.,   0.,   0.,   1.],
       [ 34.,  98.,   1.,   0.,   1.,   0.,   1.],
       [ 72.,  99.,   1.,   0.,   0.,   0.,   0.],
       [ 70., 103.,   1.,   0.,   1.,   0.,   1.],
       [ 24., 102.,   0.,   0.,   0.,   0.,   1.],
       [ 64., 102.,   1.,   0.,   0.,   0.,   0.],
       [ 49., 101.,   0.,   1.,   0.,   0.,   0.],
       [ 19., 101.,   0.,   0.,   0.,   1.,   0.],
       [ 48., 103.,   0.,   0.,   1.,   0.,   0.],
       [ 75., 104.,   0.,   1.,   0.,   0.,   1.],
       [ 25.,  99.,   0.,   0.,   1.,   0.,   1.],
       [ 65., 101.,   0.,   0.,   0.,   1.,   0.],
       [ 38., 101.,   0.,   0.,   0.,   0.,   0.],
       [ 27., 100.,   1.,   0.,   1.,   0.,   0.],
       [  5., 102.,   1.,   0.,

In [30]:
X_train_transformed.shape

(80, 7)

2. Using ColumnTransformer

In [31]:
from sklearn.compose import ColumnTransformer

In [35]:
ct = ColumnTransformer(transformers=[
    ('tf1',SimpleImputer(),['fever']),
    ('tf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tf3',OneHotEncoder(sparse=False,drop='first'),['gender','city']),
],remainder='passthrough')

In [40]:
ct_train_data = ct.fit_transform(X_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [41]:
ct_train_data.shape

(80, 7)

In [43]:
ct_test_data = ct.transform(X_test)

In [44]:
ct_test_data.shape

(20, 7)